/* Generated by BuildNumber Version 0.8 */

#ifndef HAPBUILDNUMBER_HPP_ 
#define HAPBUILDNUMBER_HPP_ 

#define HOMEKIT_VERSION_BUILD 152
#define HOMEKIT_VERSION_BUILD_STR "152" 

#endif /* HAPBUILDNUMBER_HPP_ */
