/* Generated by BuildNumber Version 0.8 */

#ifndef HAPBUILDNUMBER_HPP_ 
#define HAPBUILDNUMBER_HPP_ 

#define HOMEKIT_VERSION_BUILD 147
#define HOMEKIT_VERSION_BUILD_STR "147" 

#endif /* HAPBUILDNUMBER_HPP_ */
