//
// HAPCharacteristicType.hpp
// Homekit
//
//  Created on: 10.07.2021
//      Author: michael
//
// Bluetooth Characteristics:
// 
// HAP_CHARACTERISTIC_BLUETOOTH_PAIR_SETUP             = 0x4C,
// HAP_CHARACTERISTIC_BLUETOOTH_PAIR_VERIFY            = 0x4E,
// HAP_CHARACTERISTIC_BLUETOOTH_PAIRING_FEATURE        = 0x4F,
// HAP_CHARACTERISTIC_BLUETOOTH_PAIRINGS               = 0x50,
// HAP_CHARACTERISTIC_BLUETOOTH_SERVICE_INSTANCE_ID    = 0x51,
// 
#ifndef HAPCHARACTERISTICTYPE_HPP_
#define HAPCHARACTERISTICTYPE_HPP_

enum class HAPCharacteristicType : uint16_t {
    None                                     = 0x0000,      // Internal only
    AdministratorOnlyAccess                  = 0x0001,
    AudioFeedback                            = 0x0005,
    Brightness                               = 0x0008,
    CoolingThresholdTemperature              = 0x000D,
    CurrentDoorState                         = 0x000E,
    CurrentHeatingCoolingState               = 0x000F,
    CurrentRelativeHumidity                  = 0x0010,
    CurrentTemperature                       = 0x0011,
    HeatingThresholdTemperature              = 0x0012,
    Hue                                      = 0x0013,
    Identify                                 = 0x0014,
    LockControlPoint                         = 0x0019,
    LockManagementAutoSecurityTimeout        = 0x001A,
    LockLastKnownAction                      = 0x001C,
    LockCurrentState                         = 0x001D,
    LockTargetState                          = 0x001E,
    Logs                                     = 0x001F,
    Manufacturer                             = 0x0020,
    Model                                    = 0x0021,
    MotionDetected                           = 0x0022,
    Name                                     = 0x0023,
    ObstructionDetected                      = 0x0024,
    On                                       = 0x0025,
    OutletInUse                              = 0x0026,
    RotationDirection                        = 0x0028,
    RotationSpeed                            = 0x0029,
    Saturation                               = 0x002F,
    SerialNumber                             = 0x0030,
    TargetDoorState                          = 0x0032,
    TargetHeatingCoolingState                = 0x0033,
    TargetRelativeHumidity                   = 0x0034,
    TargetTemperature                        = 0x0035,
    TemperatureDisplayUnits                  = 0x0036,
    Version                                  = 0x0037,
    PairSetup                                = 0x004C,
    PairVerify                               = 0x004E,
    PairingFeatures                          = 0x004F,
    PairingPairings                          = 0x0050,
    FirmwareRevision                         = 0x0052,
    HardwareRevision                         = 0x0053,
    AirParticulateDensity                    = 0x0064,
    AirParticulateSize                       = 0x0065,
    SecuritySystemCurrentState               = 0x0066,
    SecuritySystemTargetState                = 0x0067,
    BatteryLevel                             = 0x0068,
    CarbonMonoxideDetected                   = 0x0069,
    ContactSensorState                       = 0x006A,
    CurrentAmbientLightLevel                 = 0x006B,
    CurrentHorizontalTiltAngle               = 0x006C,
    CurrentPosition                          = 0x006D,
    CurrentVerticalTiltAngle                 = 0x006E,
    HoldPosition                             = 0x006F,
    LeakDetected                             = 0x0070,
    OccupancyDetected                        = 0x0071,
    PositionState                            = 0x0072,
    ProgrammableSwitchEvent                  = 0x0073,
    StatusActive                             = 0x0075,
    SmokeDetected                            = 0x0076,
    StatusFault                              = 0x0077,
    StatusJammed                             = 0x0078,
    StatusLowBattery                         = 0x0079,
    StatusTampered                           = 0x007A,
    TargetHorizontalTiltAngle                = 0x007B,
    TargetPosition                           = 0x007C,
    TargetVerticalTiltAngle                  = 0x007D,
    SecuritySystemAlarmType                  = 0x008E,
    ChargingState                            = 0x008F,
    CarbonMonoxideLevel                      = 0x0090,
    CarbonMonoxidePeakLevel                  = 0x0091,
    CarbonDioxideDetected                    = 0x0092,
    CarbonDioxideLevel                       = 0x0093,
    CarbonDioxidePeakLevel                   = 0x0094,
    AirQuality                               = 0x0095,
    AccessoryFlags                           = 0x00A6,
    LockPhysicalControls                     = 0x00A7,
    TargetAirPurifierState                   = 0x00A8,
    CurrentAirPurifierState                  = 0x00A9,
    CurrentSlatState                         = 0x00AA,
    FilterLifeLevel                          = 0x00AB,
    FilterChangeIndication                   = 0x00AC,
    ResetFilterIndication                    = 0x00AD,
    TargetAirQuality                         = 0x00AE,
    CurrentFanState                          = 0x00AF,
    Active                                   = 0x00B0,
    CurrentHeaterCoolerState                 = 0x00B1,
    TargetHeaterCoolerState                  = 0x00B2,
    CurrentHumidifierDehumidifierState       = 0x00B3,
    TargetHumidifierDehumidifierState        = 0x00B4,
    WaterLevel                               = 0x00B5,
    SwingMode                                = 0x00B6,
    TargetSlatState                          = 0x00BE,
    TargetFanState                           = 0x00BF,
    SlatType                                 = 0x00C0,
    CurrentTiltAngle                         = 0x00C1,
    TargetTiltAngle                          = 0x00C2,
    OzoneDensity                             = 0x00C3,
    NitrogenDioxideDensity                   = 0x00C4,
    SulphurDioxideDensity                    = 0x00C5,
    Pm2_5Density                             = 0x00C6,
    Pm10Density                              = 0x00C7,
    VocDensity                               = 0x00C8,
    RelativeHumidityDehumidifierThreshold    = 0x00C9,
    RelativeHumidityHumidifierThreshold      = 0x00CA,
    ServiceLabelIndex                        = 0x00CB,
    ServiceLabelNamespace                    = 0x00CD,
    ColorTemperature                         = 0x00CE,
    ProgramMode                              = 0x00D1,
    InUse                                    = 0x00D2,
    SetDuration                              = 0x00D3,
    RemainingDuration                        = 0x00D4,
    ValveType                                = 0x00D5,
    IsConfigured                             = 0x00D6,
    SupportedVideoStreamConfiguration        = 0x0114,
    SupportedAudioStreamConfiguration        = 0x0115,
    SupportedRtpConfiguration                = 0x0116,
    SelectedRtpStreamConfiguration           = 0x0117,
    SetupEndpoints                           = 0x0118,
    Volume                                   = 0x0119,
    Mute                                     = 0x011A,
    NightVision                              = 0x011B,
    OpticalZoom                              = 0x011C,
    DigitalZoom                              = 0x011D,
    ImageRotation                            = 0x011E,
    ImageMirroring                           = 0x011F,
    StreamingStatus                          = 0x0120
};


#endif /* HAPCHARACTERISTICTYPE_HPP_ */


