image: python:3-slim

stages:
  - build

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  GIT_SUBMODULE_STRATEGY: recursive

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    - ~/.platformio

before_script:
  - python -V               # Print out python version for debugging
  - pip install -U platformio
  - platformio update
  

patch:
  stage: build
  script:    
    - platformio run -e teensy_41
    - patch ~/.platformio/packages/framework-arduinoteensy/libraries/Entropy/Entropy.h utils/diffs/entropy.diff    

compile:
  stage: build
  script:    
    - platformio run -e teensy_41
    - patch ~/.platformio/packages/framework-arduinoteensy/libraries/Entropy/Entropy.h utils/diffs/entropy.diff

clean:
  stage: build
  script:
    - platformio run -e teensy_41 -t clean